### ISSUE TITLE
bugtracker is listed as github?

### ISSUE THREAD

**Issue by karenetheridge** [yanick/moosex-blessed-reconstruct#2]
I'm not sure if keeping the issue tracker in a personal github repo is a good idea when comaint is shared among many people -- it means new issues don't get a lot of visibility.

But, I wonder if this repo should be simply moved into the github moose organization?

**Comment by yanick** [comment]
Closing this request for now. Whenever there will be interest/need for other maintainers to jump in, we can see about moving the repo. Until then, I'll quietly chug along on my own. :-)
